[episode]
number = 8
title = "Une librairie LLM attaquée vole tous les credentials?"
slug = "une-librairie-llm-attaquée-vole-tous-les-credentials"
description = "Une librairie LLM attaquée vole tous les credentials? On en parle dans cet épisode."
tags = []
category = "Technology"
language = "fr"
explicit = false
youtube_url = "https://www.youtube.com/watch?v=lrPhfxQ_zFM"
youtube_id = "lrPhfxQ_zFM"

[episode.guests]

[files]
video = "video.mp4"

[publish]
youtube = false
spotify = true
apple = true

[youtube]
privacy = "public"
category_id = "28"
playlist = ""
made_for_kids = false

[podcast]
season = 1
episode_type = "full"
